# Generated by Django 5.2.5 on 2025-08-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_historicalcryptocurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['name']},
        ),
    ]
